config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :parts
  resources :products
  resources :technologies
  resources :vendors
  resources :departments
  resources :factories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "factories#index"
end

app/models/factory.rb
class Factory < ApplicationRecord
  validates_presence_of :name
  has_many :departments, dependent: :delete_all
  has_many :products, dependent: :delete_all
end

app/controllers/factories_controller.rb
class FactoriesController < ApplicationController
  before_action :set_factory, only: %i[ show edit update destroy ]

  # GET /factories
  def index
    @factories = Factory.all
  end

  # GET /factories/1
  def show
  end

  # GET /factories/new
  def new
    @factory = Factory.new
  end

  # GET /factories/1/edit
  def edit
  end

  # POST /factories
  def create
    need_auth(url: factories_path) do
      @factory = Factory.new(factory_params)

      if @factory.save
        redirect_to @factory, notice: "Factory was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  # PATCH/PUT /factories/1
  def update
    need_auth(url: @factory) do
      if @factory.update(factory_params)
        redirect_to @factory, notice: "Factory was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  # DELETE /factories/1
  def destroy
    need_auth(url: @factory) do
      @factory.destroy
      redirect_to factories_url, notice: "Factory was successfully destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_factory
      @factory = Factory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def factory_params
      params.require(:factory).permit(:name, :address, :director_name)
    end
end

app/helpers/factories_helper.rb
module FactoriesHelper
end

app/views/factories/_factory.html.erb
<div id="<%= dom_id factory %>">
  <p>
    <strong>Name:</strong>
    <%= factory.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= factory.address %>
  </p>

  <p>
    <strong>Director name:</strong>
    <%= factory.director_name %>
  </p>

</div>

app/views/factories/_form.html.erb
<%= form_with(model: factory) do |form| %>
  <% if factory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(factory.errors.count, "error") %> prohibited this factory from being saved:</h2>

      <ul>
        <% factory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required: true%>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :director_name, style: "display: block" %>
    <%= form.text_field :director_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/factories/edit.html.erb
<h1>Editing factory</h1>

<%= render "form", factory: @factory %>

<br>

<div>
  <%= link_to "Show this factory", @factory %> |
  <%= link_to "Back to factories", factories_path %>
</div>

app/views/factories/index.html.erb
<h1>Factories</h1>

<div id="factories" style="overflow-x: auto">
  <table style="white-space: nowrap">
    <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Address</th>
      <th>Director name</th>
      <th colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
      <% @factories.each do |factory| %>
        <tr>
          <td> <%= factory.id %></td>
          <td> <%= factory.name %></td>
          <td> <%= factory.address %></td>
          <td> <%= factory.director_name %></td>
          <td> <%= link_to 'Show', factory %></td>
          <td> <%= link_to 'Edit', edit_factory_path(factory) %></td>
          <td> <%= link_to 'Destroy', factory, method: :delete, confirm: 'Are you sure?' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New factory", new_factory_path %>

app/views/factories/new.html.erb
<h1>New factory</h1>

<%= render "form", factory: @factory %>

<br>

<div>
  <%= link_to "Back to factories", factories_path %>
</div>

app/views/factories/show.html.erb
<%= render @factory %>

<div>
  <%= link_to "Edit this factory", edit_factory_path(@factory) %> |
  <%= link_to "Back to factories", factories_path %>

  <%= button_to "Destroy this factory", @factory, method: :delete %>
</div>