config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :parts
  resources :products
  resources :technologies
  resources :vendors
  resources :departments
  resources :factories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "factories#index"
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  validates_presence_of :name
  has_many :parts, dependent: :delete_all
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: %i[ show edit update destroy ]

  # GET /vendors
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  def create
    need_auth(url: vendors_path) do
      @vendor = Vendor.new(vendor_params)

      if @vendor.save
        redirect_to @vendor, notice: "Vendor was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  # PATCH/PUT /vendors/1
  def update
    need_auth(url: @vendor) do
      if @vendor.update(vendor_params)
        redirect_to @vendor, notice: "Vendor was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  # DELETE /vendors/1
  def destroy
    need_auth(url: @vendor) do
      @vendor.destroy
      redirect_to vendors_url, notice: "Vendor was successfully destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vendor_params
      params.require(:vendor).permit(:name, :region, :address, :director_name)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_with(model: vendor) do |form| %>
  <% if vendor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
        <% vendor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :region, style: "display: block" %>
    <%= form.text_field :region %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :director_name, style: "display: block" %>
    <%= form.text_field :director_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/vendors/_vendor.html.erb
<div id="<%= dom_id vendor %>">
  <p>
    <strong>Name:</strong>
    <%= vendor.name %>
  </p>

  <p>
    <strong>Region:</strong>
    <%= vendor.region %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= vendor.address %>
  </p>

  <p>
    <strong>Director name:</strong>
    <%= vendor.director_name %>
  </p>

</div>

app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render "form", vendor: @vendor %>

<br>

<div>
  <%= link_to "Show this vendor", @vendor %> |
  <%= link_to "Back to vendors", vendors_path %>
</div>

app/views/vendors/index.html.erb
<h1>Vendors</h1>

<div id="vendors" style="overflow-x: auto">
  <table style="white-space: nowrap">
    <thead>
    <tr>
      <th>Id</th>
      <th>Region</th>
      <th>Address</th>
      <th>Director name</th>
      <th colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td> <%= vendor.id %></td>
        <td> <%= vendor.region %></td>
        <td> <%= vendor.address %></td>
        <td> <%= vendor.director_name %></td>
        <td> <%= link_to 'Show', vendor %></td>
        <td> <%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td> <%= link_to 'Destroy', vendor, method: :delete, confirm: 'Are you sure?' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>


<%= link_to "New vendor", new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render "form", vendor: @vendor %>

<br>

<div>
  <%= link_to "Back to vendors", vendors_path %>
</div>

app/views/vendors/show.html.erb
<%= render @vendor %>

<div>
  <%= link_to "Edit this vendor", edit_vendor_path(@vendor) %> |
  <%= link_to "Back to vendors", vendors_path %>

  <%= button_to "Destroy this vendor", @vendor, method: :delete %>
</div>