config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :parts
  resources :products
  resources :technologies
  resources :vendors
  resources :departments
  resources :factories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "factories#index"
end

app/models/technology.rb
class Technology < ApplicationRecord
  validates_presence_of :duration
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: %i[ show edit update destroy ]

  # GET /technologies
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  def create
    need_auth(url: technologies_url) do
      @technology = Technology.new(technology_params)

      if @technology.save
        redirect_to @technology, notice: "Technology was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  # PATCH/PUT /technologies/1
  def update
    need_auth(url: @technology) do
      if @technology.update(technology_params)
        redirect_to @technology, notice: "Technology was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  # DELETE /technologies/1
  def destroy
    need_auth(url: @technology) do
      @technology.destroy
      redirect_to technologies_url, notice: "Technology was successfully destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def technology_params
      params.require(:technology).permit(:description, :developer, :duration)
    end
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/technologies/_form.html.erb
<%= form_with(model: technology) do |form| %>
  <% if technology.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

      <ul>
        <% technology.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :developer, style: "display: block" %>
    <%= form.text_field :developer %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/technologies/_technology.html.erb
<div id="<%= dom_id technology %>">
  <p>
    <strong>Description:</strong>
    <%= technology.description %>
  </p>

  <p>
    <strong>Developer:</strong>
    <%= technology.developer %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= technology.duration %>
  </p>

</div>

app/views/technologies/edit.html.erb
<h1>Editing technology</h1>

<%= render "form", technology: @technology %>

<br>

<div>
  <%= link_to "Show this technology", @technology %> |
  <%= link_to "Back to technologies", technologies_path %>
</div>

app/views/technologies/index.html.erb
<h1>Technologies</h1>

<div id="technologies" style="overflow-x: auto">
  <table style="white-space: nowrap">
    <thead>
    <tr>
      <th>Id</th>
      <th>Description</th>
      <th>Developer</th>
      <th>Duration</th>
      <th colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td> <%= technology.id %></td>
        <td> <%= technology.description %></td>
        <td> <%= technology.developer %></td>
        <td> <%= technology.duration %></td>
        <td> <%= link_to 'Show', technology %></td>
        <td> <%= link_to 'Edit', edit_technology_path(technology) %></td>
        <td> <%= link_to 'Destroy', technology, method: :delete, confirm: 'Are you sure?' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New technology", new_technology_path %>

app/views/technologies/new.html.erb
<h1>New technology</h1>

<%= render "form", technology: @technology %>

<br>

<div>
  <%= link_to "Back to technologies", technologies_path %>
</div>

app/views/technologies/show.html.erb
<%= render @technology %>

<div>
  <%= link_to "Edit this technology", edit_technology_path(@technology) %> |
  <%= link_to "Back to technologies", technologies_path %>

  <%= button_to "Destroy this technology", @technology, method: :delete %>
</div>